### ISSUE TITLE
Add Javascript project ideas

### ISSUE THREAD

**Issue by prdx23** [devsoc/Disco#4]

**Comment by barbier** [comment]
How about:

Create functions to understand the lexical scope and hoisting;
Iterate an array to understand "this";
Validate a form using regex;
Build something with an open API to learn AJAX;

**Comment by thinker3197** [comment]
@barbier these are great exercises to learn basics of JS, but we're looking specifically for `project` ideas (like a Github trends web-app like [this](gitlogs.com). It would be really helpful of you if you could curate some projects ideas and contribute to this repo.

**Comment by manishbisht** [comment]
Where we have to add the projects list ? In "Disco/Programming Languages/JavaScript/" we have to create another file for projects or add it in the Getting Started File
